### ISSUE TITLE
Flashing fails: usb_bulk_send() ERROR -7: Operation timed out

### ISSUE THREAD

**Issue by didier9** [Thore-Krug/Flash-CHIP#21]
I get this message a few seconds after the _waiting for fel...OK_ message.
I use an external supply to power the CHIP as recommended.
This CHIP was sick, I believe the original distribution must have been corrupted and the device did not enable the UART over USB and there was no evidence the device booted (no ssh even though it had been configured and was running before the device failed).
When I connect the FEL pin to ground and connect the USB to a Windows 10 PC, the PC does detect a USB device (not a COM port), so that gave me hope the hardware was not completely toast.
I use a Raspberry Pi B+ to install and run the tools.
The first time I ran the Flash.sh tool, it did download and build a bunch of stuff (I also had to install git first).
When it failed, I rebooted and retried a few times. After the first time it did not have to build anything and went into the "waiting for fel...OK" pretty quickly. I got the same error message each time though.

I do have a second CHIP that is working with the original Jessie distro, which I would like to upgrade since there is no software available for Jessie any longer, but I would rather try to save this one first...

Thanks for what looks like a great tool (if I can get it to work...) and thanks in advance for any further help.
Didier
![Flash-1](https://user-images.githubusercontent.com/3430458/73042265-35c4f100-3e26-11ea-9f39-3c6d57282780.png)

**Comment by didier9** [comment]
Additional information, outputs from dmesg and lsusb:
![Flash-2](https://user-images.githubusercontent.com/3430458/73077822-8e2bdb00-3e86-11ea-89f8-3507675e708f.png)

**Comment by didier9** [comment]
Also I had a scope on the 5V going to the CHIP (CHG-IN) and it is perfectly stable during the operation.

**Comment by lucasrainett** [comment]
I'm having the same problem, also checked the voltage, and tried from different computers
The problem happens when running

from Ubuntu VM on Windows 10 Host and running
from a raspberry Pi 4
from ChromeOS laptop

**Comment by didier9** [comment]
I saw this post from a little while ago:
"Error -7 is a libusb problem which is mostly caused by bad cable"
But as I posted earlier, I did check the voltage on the CHIP with an oscilloscope and it is stable (I use an external 2A lab supply to power the CHIP). The R-Pi is powered from a 2A USB supply (which I bought from Adafruit with my first R-Pi). I communicate with the R-Pi via ssh, there is no direct connection to the PC.
The USB cable is the one that came with one of my Motorola phones and they are quite good.

**Comment by subinsebastien** [comment]
I see this problem too.

**Comment by scheckley** [comment]
It's not necessarily the cable. Check your version of sunxi-tools.  I encountered this problem with Debian 10 which has the current stable sunxi-tools version 4.1.2. I rolled back to version 4.1.1-1 and the script then worked for my pocketchip (don't forget to comment out sunxi-tools from the apt install line in the script).

**Comment by dementio** [comment]
Rolling back to sunxi-tools fixed my "usb_bulk_send() ERROR -7: Operation timed out" issue as well.

**Comment by ReubenBTalbott** [comment]
This should now be fixed, the script installs an older version of sunxi-tools, it was tested on ubuntu but don't know if it works on debian though it should.

**Comment by coffe** [comment]
Hey! I have tried changing cables and ports on my computer. But I still get "usb_bulk_send () ERROR -7: Operation timed out".

My sunxi-tools version (1.4.2 + git20181114.6d598a-3). 

I can't find 4.1.1-1 that is mentioned above.

I am on Debian Stable 10 Buster :)

**Comment by Jonah6411** [comment]
> Hey! I have tried changing cables and ports on my computer. But I still get "usb_bulk_send () ERROR -7: Operation timed out".
> 
> My sunxi-tools version (1.4.2 + git20181114.6d598a-3).
> 
> I can't find 4.1.1-1 that is mentioned above.
> 
> I am on Debian Stable 10 Buster :)

I cannot find that version either and I am on the same version of sunxi-tools
I'm on Ubuntu 20.04 LTS

**Comment by scheckley** [comment]
> > Hey! I have tried changing cables and ports on my computer. But I still get "usb_bulk_send () ERROR -7: Operation timed out".
> > My sunxi-tools version (1.4.2 + git20181114.6d598a-3).
> > I can't find 4.1.1-1 that is mentioned above.
> > I am on Debian Stable 10 Buster :)
> 
> I cannot find that version either and I am on the same version of sunxi-tools
> I'm on Ubuntu 20.04 LTS

does this work? https://debian.pkgs.org/9/debian-main-amd64/sunxi-tools_1.4.1-1_amd64.deb.html

**Comment by Emzy** [comment]
> > > Hey! I have tried changing cables and ports on my computer. But I still get "usb_bulk_send () ERROR -7: Operation timed out".
> > > My sunxi-tools version (1.4.2 + git20181114.6d598a-3).
> > > I can't find 4.1.1-1 that is mentioned above.
> > > I am on Debian Stable 10 Buster :)
> > 
> > 
> > I cannot find that version either and I am on the same version of sunxi-tools
> > I'm on Ubuntu 20.04 LTS
> 
> does this work? https://debian.pkgs.org/9/debian-main-amd64/sunxi-tools_1.4.1-1_amd64.deb.html

This fixes it for me on Debian 10 (Raspberry PI4)

**Comment by bestouff** [comment]
I confirm the fix.

**Comment by cqwer** [comment]
fix doesn't work, because the script automatically updates the sunxy version to 1.4.2 again, which causes the bulk error

**Comment by TerraRoot** [comment]
same issue, downgraded with a deb and comment out the package in the script to stop it updating again until i was done flashing my chip, happy to have it back working again!

**Comment by edo9k** [comment]
Confirming sunxi-tools downgrade fix.

**Comment by pablonoel** [comment]
I had the same problem using a RPI4, installed the sunxi tool with no avail. 

Reading the oficial Next Thing documentation it says:

"If you are using a computer with USB3 ports, it’s suggested that you attach a USB2-compliant hub and connect your CHIP to the hub, instead of directly to the USB3 port." 

So I switched from the usb3 port to the usb2 port of my RPi4 and it worked perfectly fine.

**Comment by dorin131** [comment]
Here is how you downgrade **sunxi-tools** on newer versions of Ubuntu based distros.

- Append `deb http://de.archive.ubuntu.com/ubuntu/ bionic main universe` to `/etc/apt/sources.list`
- Do `sudo apt update`
- Install the package: `sudo apt install sunxi-tools=1.4.1-1`
- Mark hold to prevent upgrade: `apt-mark hold sunxi-tools`
- To prevent any other complications Remove `deb http://de.archive.ubuntu.com/ubuntu/ bionic main universe` from `/etc/apt/sources.list`

Then you can flash.

**Comment by wersimmon** [comment]
Here is how you can downgrade sunxi-tools on Debian

- Add a source that has the older version of sunxi-tools: `nano /etc/apt/sources.list` and append `deb http://deb.debian.org/debian/ stretch main`
- Update apt's cache: `sudo apt update`
- Install the package: `sudo apt install sunxi-tools=1.4.1-1`
- Mark hold to prevent it from being upgraded: `apt-mark hold sunxi-tools`
- To avoid complications you can remove `stretch main` from the sources.list again

**Comment by TroyFletcher** [comment]
> > > Hey! I have tried changing cables and ports on my computer. But I still get "usb_bulk_send () ERROR -7: Operation timed out".
> > > My sunxi-tools version (1.4.2 + git20181114.6d598a-3).
> > > I can't find 4.1.1-1 that is mentioned above.
> > > I am on Debian Stable 10 Buster :)
> > 
> > 
> > I cannot find that version either and I am on the same version of sunxi-tools
> > I'm on Ubuntu 20.04 LTS
> 
> does this work? https://debian.pkgs.org/9/debian-main-amd64/sunxi-tools_1.4.1-1_amd64.deb.html

Downloading this deb file, and downgrading fixed the issue, but you must comment out the flash.sh script's apt install of the tools, as this will re-upgrade the package you just downgraded.

Running Flash.sh with the sunxi-tools 1.4.1-1 solved the issue for me!

**Comment by yopuz** [comment]
I have to plug the cable when the message appears, not before, as I read in other script instructions, worked inmediately.

**Comment by NikitaYarkin** [comment]
Hi all. I have a problem with fastboot. My CHIP is disconnected along with the USB port when I try to flash it. What could be wrong?I tried applying +5 volts to CHG-IN  and  two different data-cables but it didn't help.

![2024-11-18_15-10-01](https://github.com/user-attachments/assets/a645585d-3b8d-4b43-851a-7651deb43f9d)

Here are my versions of the required packages:

![Снимок экрана_2024-11-18_15-28-17](https://github.com/user-attachments/assets/263f3119-fe2f-481b-a94d-c471d1913fa7)

**Comment by sridharrajagopal** [comment]
Unfortunately, even with downgrading sunxi-tools-1.4.1-1 I had the same error. 

I'm trying it on a Raspberry Pi 5 with Bookworm btw. 

Thanks,
Sridhar

UPDATE - I tried it with the spare chip I had (came with the fulfillment from kickstarter), and that is getting flashed properly, so the one that was attached to the pocketchip must have an issue (though I'd powered it on once, and then it sat in my closet collecting dust, so never used).

**Comment by NikitaYarkin** [comment]
Im flashed my CHIP on raspberry pi too.
--
Отправлено из Mail.ru для Android понедельник, 20 января 2025г., 23:22 +03:00 от Sridhar Rajagopal  ***@***.*** :

**Comment by sridharrajagopal** [comment]
It looks like the unit I'm having trouble with might be experiencing the problem in issue : https://github.com/Thore-Krug/Flash-CHIP/issues/17

I'm still investigating that.

**Comment by a8750136** [comment]
> Rolling back to sunxi-tools fixed my "usb_bulk_send() ERROR -7: Operation timed out" issue as well.

Rolling back  sunxi-tools-1.4.1-1 dosn't work for me. 
And then I did "git clone https://github.com/linux-sunxi/sunxi-tools" to get the latest version ( commit 7540cb235691be94ac5ef0181a73dd929949fc4e ) and tried to do the "make install-all install-misc" to rebuild sunxi-tools. 
And I encounterred many errors.

Following are the instruction I've called for solving build problems (not sure which ones are actually make "make" working):
sudo apt-get install gcc-arm-none-eabi
apt install libc6-dev
sudo apt-get install --reinstall libc6-dev
apt-get install libusb-1.0-0-dev zlib1g-dev
sudo apt install libusb-1.0-0-dev
sudo apt install sunxi-tools
sudo apt-get install libfdt-dev

After "make install-all install-misc" successfully done, re-do Flash.sh. 
This time "usb_bulk_send() ERROR -7" not showing up again and I got "FLASH VERIFICATION COMPLETE".
Hope this experience could help.
 
Note: I'm using "Ubuntu 20.04.6 LTS"

**Comment by EncrowThorne19** [comment]
> > > > 嗨！我尝试更换了电脑上的线缆和端口，但仍然出现“usb_bulk_send () ERROR -7: Operation timed out”的错误。
> > > > 我的 sunxi-tools 版本是 1.4.2 + git20181114.6d598a-3。
> > > > 我找不到上面提到的 4.1.1-1 版本。
> > > > 我的系统是 Debian Stable 10 Buster :)
> > > 
> > > 
> > > 我也找不到那个版本，而且我的 sunxi-tools 版本和你一样，
> > > 我的系统是 Ubuntu 20.04 LTS。
> > 
> > 
> > 这个能用吗？https://debian.pkgs.org/9/debian-main-amd64/sunxi-tools_1.4.1-1_amd64.deb.html
> 
> 下载此 deb 文件并降级后问题得到解决，但您必须注释掉 flash.sh 脚本中对工具的 apt 安装，因为这将重新升级您刚刚降级的软件包。
> 
> 使用 sunxi-tools 1.4.1-1 运行 Flash.sh 解决了我的问题！

The problem has been resolved
